#----------------------
# About section

blurb: <p><strong>Xin Liu is .....</p>

#----------------------
# Courses section
courses:
  - {title: Intro to Chem, semester: Fall 1885, school:  description: Teaching students economics isn't only for witches., link: courses/temp_course }
  - {title: Advanced Psychiatric Medicine, semester: Spring 1885, school: : At the time, mainly lobotomy., link: courses/temp_course }
  - {title: Diseases of the Mind, semester: Fall 1884, school:   description: Survey course. Mainly taught by example., link: courses/temp_course }
#----------------------
# Contact
contact-info: <p>Xin Liu<br>Michigan State University<br>Department of Economics<br>United States</p>

contact-links:
  - {contact-text: Github, contact-link: "https://www.google.com", icon: 'favicon.html'}
